export const populationDatas=[
  {
    name:'出生日期：',
    keys:'birthday',
    id:1,
    types:'date',
  },
  {
    name:'性别：',
    keys:'gender',
    id:2,
    types:'radio',
    children:[
      {
        name:'男',
        id:3,
        value:1,
      },
      {
        name:'女',
        id:4,
        value:2,
      }
    ]
  },
  {
    name:'民族：',
    keys:'nation',
    id:5,
    types:'radio',
    children:[
      {
        name:'汉族',
        id:6,
        value:1,
      },
      {
        name:'其他，请说明',
        value:2,
        id:7,
        types:'input',
        children:{
          keys:'nation_other',
        }
      }
    ]
  },
  {
    name:'婚否：',
    keys:'marriage',
    id:8,
    types:'radio',
    children:[
      {
        name:'是',
        id:9,
        value:1,
      },
      {
        name:'否',
        id:10,
        value:0,
      }
    ]
  },
  {
    name:'身高：',
    keys:'height',
    id:11,
    types:'inputNumber',
  },
  {
    name:'体重：',
    keys:'weight',
    id:12,
    types:'inputNumber',
  },
  {
    name:'重要病史：',
    id:13,
    keys:'import_sickness_history',
    types:'textArea',
  },
  {
    name:'药物过敏史：',
    keys:'drug_allergy_history',
    id:14,
    types:'radio',
    children:[
      {
        name:'无',
        id:15,
        value:0,
      },
      {
        name:'有，若有，请说明',
        value:1,
        id:16,
        types:'input',
        children:{
          keys:'drug_allergy_history_specific',
          id:17,
        }
      }
    ]
  },
  {
    name:'医疗费用来源：',
    keys:'expenses_source',
    id:18,
    types:'radio',
    children:[
      {
        name:'公费',
        id:19,
        value:1,
      },
      {
        name:'基本医疗保险',
        id:20,
        value:2,
      },
      {
        name:'商业保险',
        id:21,
        value:3,
      },
      {
        name:'农村合作医疗',
        id:22,
        value:4,
      },
      {
        name:'自费',
        id:23,
        value:5,
      },
      {
        name:'其他',
        id:24,
        value:6,
      },
    ]
  },
]
export const lifeDatas=[
  {
    name:'体温：',
    keys:'temperature',
    id:1,
    types:'inputNumber',
  },
  {
    name:'呼吸：',
    keys:'breathe_num',
    id:2,
    types:'inputNumber',
  },
  {
    name:'心率：',
    keys:'heart_rate',
    id:3,
    types:'inputNumber',
  },
  {
    name:'血压：',
    keys:'sbp',
    id:4,
    types:'inputNumber',
  },
]
export const physiqueDatas=[
  {
    name:'皮肤、粘膜：',
    keys:'skin_mucosa',
    id:1,
    types:'radio',
    children:[
      {
        name:'正常',
        id:2,
        value:1,
      },
      {
        name:'异常，异常情况描述',
        value:2,
        id:3,
        types:'input',
        children:{
          keys:'skin_mucosa_abnormal',
          id:4,
        }
      },
      {
        name:'未查',
        id:5,
        value:3,
      },
    ]
  },
  {
    name:'淋巴结：',
    keys:'lymph_gland',
    id:6,
    types:'radio',
    children:[
      {
        name:'正常',
        id:7,
        value:1,
      },
      {
        name:'异常，异常情况描述',
        value:2,
        id:8,
        types:'input',
        children:{
          keys:'lymph_gland_abnormal',
          id:9,
        }
      },
      {
        name:'未查',
        id:10,
        value:3,
      },
    ]
  },
  {
    name:'头颈部：',
    keys:'neck',
    id:11,
    types:'radio',
    children:[
      {
        name:'正常',
        id:12,
        value:1,
      },
      {
        name:'异常，异常情况描述',
        value:2,
        id:13,
        types:'input',
        children:{
          keys:'neck_gland_abnormal',
          id:14,
        }
      },
      {
        name:'未查',
        id:15,
        value:3,
      },
    ]
  },
  {
    name:'胸部：',
    keys:'chest',
    id:16,
    types:'radio',
    children:[
      {
        name:'正常',
        id:17,
        value:1,
      },
      {
        name:'异常，异常情况描述',
        value:2,
        id:18,
        types:'input',
        children:{
          keys:'chest_abnormal',
          id:19,
        }
      },
      {
        name:'未查',
        id:20,
        value:3,
      },
    ]
  },
  {
    name:'腹部：',
    keys:'abdomen',
    id:21,
    types:'radio',
    children:[
      {
        name:'正常',
        id:22,
        value:1,
      },
      {
        name:'异常，异常情况描述',
        value:2,
        id:23,
        types:'input',
        children:{
          keys:'abdomen_abnormal',
          id:24,
        }
      },
      {
        name:'未查',
        id:25,
        value:3,
      },
    ]
  },
  {
    name:'脊柱：',
    keys:'spine',
    id:26,
    types:'radio',
    children:[
      {
        name:'正常',
        id:27,
        value:1,
      },
      {
        name:'异常，异常情况描述',
        value:2,
        id:28,
        types:'input',
        children:{
          keys:'spine_abnormal',
          id:29,
        }
      },
      {
        name:'未查',
        id:30,
        value:3,
      },
    ]
  },
  {
    name:'肌肉骨骼：',
    keys:'musculoskeletal',
    id:31,
    types:'radio',
    children:[
      {
        name:'正常',
        id:32,
        value:1,
      },
      {
        name:'异常，异常情况描述',
        value:2,
        id:33,
        types:'input',
        children:{
          keys:'musculoskeletal_abnormal',
          id:34,
        }
      },
      {
        name:'未查',
        id:35,
        value:3,
      },
    ]
  },
  {
    name:'神经系统：',
    keys:'nervous_system',
    id:36,
    types:'radio',
    children:[
      {
        name:'正常',
        id:37,
        value:1,
      },
      {
        name:'异常，异常情况描述',
        value:2,
        id:38,
        types:'input',
        children:{
          keys:'nervous_system_abnormal',
          id:39,
        }
      },
      {
        name:'未查',
        id:40,
        value:3,
      },
    ]
  },
  {
    name:'其他：',
    keys:'other',
    id:41,
    types:'radio',
    children:[
      {
        name:'正常',
        id:42,
        value:1,
      },
      {
        name:'异常，异常情况描述',
        value:2,
        id:43,
        types:'input',
        children:{
          keys:'other_abnormal',
          id:44,
        }
      },
      {
        name:'未查',
        id:45,
        value:3,
      },
    ]
  },
]
export const badDatas=[
  {
    name:'不良事件名称：',
    keys:'name',
    id:1,
    types:'input',
  },
  {
    name:'开始发生日期（年/月/日）：',
    keys:'start_date',
    id:2,
    types:'date',
  },
  {
    name:'终止日期（年/月/日）：',
    keys:'end_date',
    id:3,
    types:'date',
  },
  {
    name:'严重程度：',
    keys:'severity_id',
    id:4,
    transverse:true,
    types:'radio',
    children:[
      {
        name:'轻',
        id:5,
        value:1,
      },
      {
        name:'中',
        id:6,
        value:2,
      },
      {
        name:'重',
        id:7,
        value:3,
      }
    ]
  },
  {
    name:'采取措施：',
    keys:'measure_id',
    id:8,
    transverse:false,
    types:'radio',
    children:[
      {
        name:'无任何措施',
        id:9,
        value:1,
      },
      {
        name:'暂停用药/剂量调整',
        id:10,
        value:2,
      },
      {
        name:'中止试验',
        id:11,
        value:3,
      },
      {
        name:'采取合并用药',
        id:12,
        value:4,
      },
      {
        name:'住院或着住院延长',
        id:13,
        value:5,
      },
    ]
  },
  {
    name:'与研究药物的关系：',
    keys:'medicine_id',
    id:14,
    transverse:false,
    types:'radio',
    children:[
      {
        name:'肯定',
        id:15,
        value:1,
      },
      {
        name:'很可能',
        id:16,
        value:2,
      },
      {
        name:'可能',
        id:17,
        value:3,
      },
      {
        name:'可能无关',
        id:18,
        value:4,
      },
      {
        name:'肯定无关',
        id:19,
        value:5,
      },
    ]
  },
  {
    name:'是否严重不良事件：',
    keys:'serious_id',
    id:20,
    transverse:true,
    types:'radio',
    children:[
      {
        name:'是',
        id:21,
        value:1,
      },
      {
        name:'否',
        id:22,
        value:0,
      },
    ]
  },
  {
    name:'不良事件的结局（在不良事件终止或研究结束时填写此栏）：',
    keys:'end_id',
    id:23,
    transverse:false,
    types:'radio',
    children:[
      {
        name:'痊愈',
        id:24,
        value:1,
      },
      {
        name:'缓解',
        id:25,
        value:2,
      },
      {
        name:'无改变',
        id:26,
        value:3,
      },
      {
        name:'加重',
        id:27,
        value:4,
      },
      {
        name:'死亡',
        id:28,
        value:5,
      },
      {
        name:'失访',
        id:29,
        value:6,
      },
    ]
  },
  {
    name:'不良事件补充说明：',
    id:30,
    keys:'explain',
    types:'textArea',
  },
]